### ISSUE TITLE
Configure and make on Oracle Solaris 11.4

### ISSUE THREAD

**Issue by fwerfewrfwref** [unfs3/unfs3#24]
I have tried compiling on Oracle Solaris 11.4 x86.
./configure failed

_./configure
checking for a BSD-compatible install... /usr/bin/ginstall -c
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for ar... ar
checking for flex... no
checking for lex... lex
checking lex output file root... lex.yy
checking lex library... -ll
checking whether yytext is a pointer... no
checking for bison... no
checking for byacc... no
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/xpg4/bin/grep
checking for egrep... /usr/xpg4/bin/grep -E
checking for ANSI C header files... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for library containing xdr_int... none required
checking for library containing socket... none required
checking for library containing inet_aton... none required
checking for mntent.h... no
checking for stdint.h... yes
checking for sys/mnttab.h... yes
checking for sys/mount.h... yes
checking for sys/vmount.h... no
checking for rpc/svc_soc.h... yes
checking for linux/ext2_fs.h... no
checking for int32... no
checking for uint32... no
checking for int64... no
checking for uint64... no
checking for struct stat.st_gen... no
checking for statvfs... yes
checking for seteuid... yes
checking for setegid... yes
checking for setresuid... no
checking for setresgid... no
checking for vsyslog... yes
checking for lchown... yes
checking for setgroups... yes
./configure: line 4139: syntax error at line 4143: `(' unexpected_

I commented out line 4143 after checking "pkg search rpc" if libtirpc needs to be installed.
Info: https://docs.oracle.com/cd/E37838_01/html/E61058/rpcintro-46812.html

_#PKG_CHECK_MODULES(TIRPC, libtirpc)_

configure now works, but make now failed with 

_make
gcc -g -O2 -Wall -W   -D_GNU_SOURCE -I.  -c  afsgettimes.c
gcc -g -O2 -Wall -W   -D_GNU_SOURCE -I.  -c  afssupport.c
gcc -g -O2 -Wall -W   -D_GNU_SOURCE -I.  -c  attr.c
attr.c: In function 'get_free_bad_dir_entry':
attr.c:560:5: warning: implicit declaration of function 'free' [-Wimplicit-function-declaration]
  560 |     free(bad_dir_cache[best].path);
      |     ^~~~
attr.c:31:1: note: include '<stdlib.h>' or provide a declaration of 'free'
   30 | #include "Config/exports.h"
  +++ |+#include <stdlib.h>
   31 | 
attr.c:560:5: warning: incompatible implicit declaration of built-in function 'free' [-Wbuiltin-declaration-mismatch]
  560 |     free(bad_dir_cache[best].path);
      |     ^~~~
attr.c:560:5: note: include '<stdlib.h>' or provide a declaration of 'free'
attr.c: In function 'find_bad_dir_entry':
attr.c:577:13: warning: implicit declaration of function 'strcmp' [-Wimplicit-function-declaration]
  577 |         if (strcmp(path, bad_dir_cache[i].path) == 0) {
      |             ^~~~~~
attr.c:31:1: note: include '<string.h>' or provide a declaration of 'strcmp'
   30 | #include "Config/exports.h"
  +++ |+#include <string.h>
   31 | 
attr.c:585:23: warning: implicit declaration of function 'strdup' [-Wimplicit-function-declaration]
  585 |     new_entry->path = strdup(path);
      |                       ^~~~~~
attr.c:585:23: warning: incompatible implicit declaration of built-in function 'strdup' [-Wbuiltin-declaration-mismatch]
gcc -g -O2 -Wall -W   -D_GNU_SOURCE -I.  -c  daemon.c
daemon.c: In function 'get_port':
daemon.c:143:45: error: 'struct sockaddr_in' has no member named 'sin6_port'; did you mean 'sin_port'?
  143 |     return (svc_getcaller(rqstp->rq_xprt))->sin6_port;
      |                                             ^~~~~~~~~
      |                                             sin_port
daemon.c:144:1: warning: control reaches end of non-void function [-Wreturn-type]
  144 | }
      | ^
*** Error code 1
make: Fatal error: Command failed for target `daemon.o'_
[unfs3.tar.gz](https://github.com/unfs3/unfs3/files/9837908/unfs3.tar.gz)

**Comment by CendioOssman** [comment]
TI-RPC is a hard requirement, so I'm not surprised that things fail if you remove that. It looks like something went wrong when you ran `./bootstrap` as that line shouldn't have been in `configure`. I'm guessing that pkg-config wasn't installed. Did you get any errors running `./bootstrap`?

**Comment by CendioOssman** [comment]
It builds fine with libtirpc 1.3.3 here at least.

**Comment by CendioOssman** [comment]
No reseponse. Closing.
